### PR TITLE
dbft: ensure non-consensus nodes function normally

### LINKED ISSUE #63: Ensure non-consensus node can function normally
Within the scope of this issue we need to make work normally all types of non-consensus nodes:
* account-less RPC node;
* light node;
* former consensus node.

What we need is to add enabled/disabled setting to the DBFT node settings, not to start consensus on missing account and allow consensus module to be run normally in case if authorized validator was kicked of the validators list.

Currently after #49 it's known that RPC node from single/four-nodes privnet is failing with panic, thanks to @nicolegys for pointing that out:
```
INFO [12-19|16:58:54.681] Loaded most recent local block           number=0 hash=05148f..9ce5ad td=1 age=54y9mo13h
WARN [12-19|16:58:54.681] Failed to load snapshot                  err="missing or corrupted snapshot"
INFO [12-19|16:58:54.690] Rebuilding state snapshot 
INFO [12-19|16:58:54.691] Regenerated local transaction journal    transactions=0 accounts=0
INFO [12-19|16:58:54.692] Initialized transaction indexer          limit=2,350,000
INFO [12-19|16:58:54.692] Resuming state snapshot generation       root=e38ad3..e797c5 accounts=0 slots=0 storage=0.00B dangling=0 elapsed=1.329ms
INFO [12-19|16:58:54.694] Generated state snapshot                 accounts=2 slots=0 storage=94.00B dangling=0 elapsed=3.409ms
INFO [12-19|16:58:54.699] Gasprice oracle is ignoring threshold set threshold=2
WARN [12-19|16:58:54.700] Engine API enabled                       protocol=eth
WARN [12-19|16:58:54.700] Engine API started but chain not configured for merge yet 
INFO [12-19|16:58:54.700] Starting peer-to-peer node               instance=Geth/v1.13.1-stable-1eea1e66/linux-amd64/go1.21.1
INFO [12-19|16:58:54.700] Stored checkpoint snapshot to disk       number=0 hash=05148f..9ce5ad
INFO [12-19|16:58:54.738] New local node record                    seq=1,702,994,334,737 id=4fb0a4c547ba54ca ip=127.0.0.1 udp=30307 tcp=30307
INFO [12-19|16:58:54.738] Started P2P networking                   self=enode://6d4769341e089301345c84f7ad6f1ad7721bcb9439c7ad4dc99c6789ce2c6dee57525bf1c3d21f817fcbeb8756d1b0c298586c31cc4468c8d3ded4109a4bea90@127.0.0.1:30307
INFO [12-19|16:58:54.740] IPC endpoint opened                      url=/home/anna/Documents/GitProjects/bane-labs/go-ethereum/privnet/single/node2/geth.ipc
INFO [12-19|16:58:54.740] Generated JWT secret                     path=/home/anna/Documents/GitProjects/bane-labs/go-ethereum/privnet/single/node2/geth/jwtsecret
INFO [12-19|16:58:54.741] WebSocket enabled                        url=ws://127.0.0.1:8553
INFO [12-19|16:58:54.741] HTTP server started                      endpoint=127.0.0.1:8553 auth=true prefix= cors=localhost vhosts=localhost
INFO [12-19|16:58:55.712] Unlocked account                         address=0x1dfbe2dF23Ef8B4a787dD8506ca3400B1Cd0B868
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe8b18a]

goroutine 4395 [running]:
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).validatePayload(0xc0005b4900, 0xc00064b960)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1274 +0x2a
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).OnPayload(0xc0005b4900, 0xc00049ff80)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1252 +0x239
github.com/ethereum/go-ethereum/eth/protocols/dbft.(*Service).HandleMessage(0xc000274540, 0xc0019f9cb0)
	github.com/ethereum/go-ethereum/eth/protocols/dbft/handler.go:105 +0x60b
github.com/ethereum/go-ethereum/eth/protocols/dbft.(*Service).Handle(0xc000274550?, 0xc0019f9cb0)
	github.com/ethereum/go-ethereum/eth/protocols/dbft/handler.go:47 +0x2d
github.com/ethereum/go-ethereum/eth/protocols/dbft.(*Service).Run(0xc000274540, 0xc00039a3f0, {0x1fda450?, 0xc000466f00?})
	github.com/ethereum/go-ethereum/eth/protocols/dbft/service.go:74 +0x172
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1()
	github.com/ethereum/go-ethereum/p2p/peer.go:426 +0x7b
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols in goroutine 4384
	github.com/ethereum/go-ethereum/p2p/peer.go:424 +0x9e
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #63.

In this PR:
* allow dBFT payloads broadcasting for non-consensus nodes;
* allow non-consensus nodes with enabled miner to participate in consensus process with "WatchOnly" status.

The overall updated node behaviour is the following:
    
* If the node is a light node, then DBFT consensus engine is created but not started. dBFT P2P protocol is not started and not processing/shearing any consensus messages. Consensus engine in this case is used for incoming blocks verification only. Miner also can't be started for light node, it's prohibited by the current Geth implementation and we're pretty OK with it.
* If the node is a full node (archival, RPC or any full non-miner node) then DBFT service is created but not started (and not initialized by account). It is used to verify incoming blocks. dBFT P2P protocol is started and used to relay consensus messages without verification (just P2P broadcasting). Miner is not started.
* If the node is a miner node, then DBFT service is created, started and initialised by etherbase account (that is potentially a validator). dBFT P2P protocol is started and used to relay consensus messages and to route consensus messages to DBFT service with preliminary verification. Miner is started and submitting tasks to DBFT service even if etherbase authorized accoint is a validator. In case if authorized account is excluded from the validators list, then the node is still a consensus member with "WatchOnly" status until it's restarted without `--miner` flag. Once authorised acconunt is included back to the validators set, then miner is allowed to submit tasks to DBFT service and DBFT service properly starts its work with "Backup" or "Primary" status.

Thus, DBFT service event loop is directly depends on miner process start and at the same time it respects the fact whether authorized account is included into validators set for the current block. The described state of things looks good to me and thus, I consider that no additional modifications should be done in DBFT engine configuration.

### CODE REVIEW

**Comment by AnnaShaleva** [comment]
@roman-khimov, please, review the comment in the PR description, that's the current state of things and I think that non-consensus nodes works as expected now. But maybe you find something that works not as expected.

**Comment by roman-khimov** [comment]
Will I get dBFT log messages in miner/not-elected (watch only) case? It's a nice thing for debugging, with NeoGo I can start a node that has no CN key and can't do much, but still see what's happening.

**Review by roman-khimov — APPROVED** [review]

**Comment by AnnaShaleva** [comment]
> Will I get dBFT log messages in miner/not-elected (watch only) case?

Yes, it works exactly like NeoGo. The only difference is that you can't start miner/not-elected without etherbase address, it's a must-have for miner, but I don't think it hurts.

**Comment by AnnaShaleva** [comment]
See the example logs from non-elected miner node:
```
2023-12-21T18:31:57.127+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:66	approving block	{"height": 1, "hash": "a7d1d58826868cd9c34f53be329b985a68b7b67abe53121e96c9a87f1040a999", "tx_count": 0, "merkle": "7a77851842736c8672a67c64093fcdae5e1991f8cee5806a2d80a4b70a9749a9", "prev": "98bb61fde1b49ef9e62992a28adfb71df99001a6dec2da1c5d534975f5611263"}
INFO [12-21|18:31:57.133] Imported new chain segment               number=1 hash=1b16ff..099db8 blocks=1 txs=0 mgas=0.000 elapsed=4.814ms     mgasps=0.000 triedirty=0.00B
2023-12-21T18:31:57.133+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 2, "height": 1, "view": 1, "my_height": 1, "my_view": 1}
2023-12-21T18:31:57.133+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 1, "height": 1, "view": 1, "my_height": 1, "my_view": 1}
INFO [12-21|18:31:57.133] Commit new sealing work                  number=2 sealhash=5d404b..1357eb txs=0 gas=0 fees=0 elapsed="491.417µs"
2023-12-21T18:31:57.133+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:107	initializing dbft	{"height": 2, "view": 0, "index": -1, "role": "WatchOnly"}
INFO [12-21|18:31:57.133] Start dBFT process for new sealing work  number=2 sealhash=5d404b..1357eb prev=1b16ff..099db8
2023-12-21T18:32:02.133+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "PrepareRequest", "from": 2, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.134+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:325	received empty PrepareRequest
2023-12-21T18:32:02.134+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:333	received PrepareRequest	{"validator": 2, "tx": 0}
2023-12-21T18:32:02.137+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "PrepareResponse", "from": 3, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.137+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:433	received PrepareResponse	{"validator": 3}
2023-12-21T18:32:02.139+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "PrepareResponse", "from": 0, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.139+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:433	received PrepareResponse	{"validator": 0}
2023-12-21T18:32:02.144+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 2, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.144+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:507	received Commit	{"validator": 2}
2023-12-21T18:32:02.144+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:57	not enough to commit	{"count": 1}
2023-12-21T18:32:02.144+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 3, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.144+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:507	received Commit	{"validator": 3}
2023-12-21T18:32:02.145+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:57	not enough to commit	{"count": 2}
2023-12-21T18:32:02.145+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 0, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.145+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:507	received Commit	{"validator": 0}
2023-12-21T18:32:02.146+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:66	approving block	{"height": 2, "hash": "9630184383a36f5630805ae573e2c741069bc63ff0e912c5829a363fff545c58", "tx_count": 0, "merkle": "7a77851842736c8672a67c64093fcdae5e1991f8cee5806a2d80a4b70a9749a9", "prev": "1b16ffecf3600c7ce71bae65c4f3a4c14760837e90246a34e8002fccb3099db8"}
INFO [12-21|18:32:02.152] Imported new chain segment               number=2 hash=3d09fe..b1b98d blocks=1 txs=0 mgas=0.000 elapsed=5.822ms     mgasps=0.000 triedirty=0.00B
2023-12-21T18:32:02.152+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 0, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.152+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 0, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.153+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 0, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
2023-12-21T18:32:02.153+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "PrepareResponse", "from": 1, "height": 2, "view": 0, "my_height": 2, "my_view": 0}
INFO [12-21|18:32:02.154] Commit new sealing work                  number=3 sealhash=17ff91..0d1d7b txs=0 gas=0 fees=0 elapsed=1.186ms
2023-12-21T18:32:02.154+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:107	initializing dbft	{"height": 3, "view": 0, "index": -1, "role": "WatchOnly"}
INFO [12-21|18:32:02.154] Start dBFT process for new sealing work  number=3 sealhash=17ff91..0d1d7b prev=3d09fe..b1b98d
2023-12-21T18:32:02.157+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 1, "height": 2, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:02.157+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:223	ignoring old height	{"height": 2}
2023-12-21T18:32:07.144+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "PrepareRequest", "from": 3, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.144+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:325	received empty PrepareRequest
2023-12-21T18:32:07.144+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:333	received PrepareRequest	{"validator": 3, "tx": 0}
2023-12-21T18:32:07.145+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "PrepareResponse", "from": 2, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.145+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:433	received PrepareResponse	{"validator": 2}
2023-12-21T18:32:07.146+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "PrepareResponse", "from": 0, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.146+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:433	received PrepareResponse	{"validator": 0}
2023-12-21T18:32:07.147+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 2, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.147+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:507	received Commit	{"validator": 2}
2023-12-21T18:32:07.147+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:57	not enough to commit	{"count": 1}
2023-12-21T18:32:07.147+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 0, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.147+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:507	received Commit	{"validator": 0}
2023-12-21T18:32:07.147+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:57	not enough to commit	{"count": 2}
2023-12-21T18:32:07.147+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 0, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.148+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 3, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.148+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:507	received Commit	{"validator": 3}
2023-12-21T18:32:07.149+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:66	approving block	{"height": 3, "hash": "f773a9c62fb4f4104560300dd1e865cfd1374ff0285f5bfaba2d900f7de99384", "tx_count": 0, "merkle": "7a77851842736c8672a67c64093fcdae5e1991f8cee5806a2d80a4b70a9749a9", "prev": "3d09fe77dbdc35ff9ff67e6f35521da42496eea10cbe276df6386e6b8db1b98d"}
INFO [12-21|18:32:07.158] Imported new chain segment               number=3 hash=7a572f..145407 blocks=1 txs=0 mgas=0.000 elapsed=8.894ms     mgasps=0.000 triedirty=0.00B
2023-12-21T18:32:07.158+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 3, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.158+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 3, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.158+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "PrepareResponse", "from": 1, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
2023-12-21T18:32:07.158+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:214	received message	{"type": "Commit", "from": 1, "height": 3, "view": 0, "my_height": 3, "my_view": 0}
INFO [12-21|18:32:07.158] Commit new sealing work                  number=4 sealhash=90cd49..6ad943 txs=0 gas=0 fees=0 elapsed="195.352µs"
2023-12-21T18:32:07.158+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:107	initializing dbft	{"height": 4, "view": 0, "index": -1, "role": "WatchOnly"}
INFO [12-21|18:32:07.158] Start dBFT process for new sealing work  number=4 sealhash=90cd49..6ad943 prev=7a572f..145407
```

So there are initialisation logs with WatchOnly status, and I've precisely checked the code that every dBFT callback is set properly to work with non-elected node.
```
2023-12-21T18:32:07.158+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:107	initializing dbft	{"height": 4, "view": 0, "index": -1, "role": "WatchOnly"}
```

**Pull request merged**
